version: '3.4'

services:

  db:
    image: mysql:5.6
    restart: always
    container_name: mysql_pizza_task
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - volumen-db:/var/lib/mysql
    network_mode: host

  app:
    image: pizza-task
    build: .
    container_name: pizza-task-container
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    command: /bin/bash -c "cd /app/apps/ && python3 manage.py migrate && python3 manage.py runserver"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    network_mode: host
    
volumes:
  volumen-db: