# Generated by Django 3.0.5 on 2020-04-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, height_field=500, null=True, upload_to='', verbose_name='photo', width_field=500)),
            ],
        ),
        migrations.CreateModel(
            name='PricePizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizes.Size')),
            ],
        ),
    ]
