# Generated by Django 3.0.5 on 2020-05-01 01:40

import base.stores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20200430_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(blank=True, height_field=500, null=True, storage=base.stores.PizzaModelStorage(), upload_to=base.stores.PizzaModelStorage.pizza_photo_path, verbose_name='photo', width_field=500),
        ),
    ]
