# Generated by Django 3.0.5 on 2020-04-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzas', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('pizza_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.PricePizza')),
            ],
        ),
        migrations.CreateModel(
            name='CommandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientByClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1)),
                ('description', models.CharField(default='', max_length=300)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.Command')),
                ('ingredient_topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.CommandStatus'),
        ),
    ]
