# Generated by Django 3.0.5 on 2020-04-28 15:39

from django.db import migrations


def load_data(apps, schema_editor):
    obj_command_status = apps.get_model("commands", "CommandStatus")
    status = [
        {
            'name': 'created',
            'description': 'created'
        },
        {
            'name': 'cooking',
            'description': 'cooking'
        },
        {
            'name': 'cooked',
            'description': 'cooked'
        },
        {
            'name': 'canceled_by_client',
            'description': 'canceled_by_client'
        },
        {
            'name': 'canceled_by_us',
            'description': 'canceled_by_us'
        },
    ]
    for element in status:
        obj_command_status(**element).save()


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
