# Generated by Django 3.0.5 on 2020-04-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_load_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commands.CommandStatus'),
        ),
    ]
