# Generated by Django 3.0.5 on 2020-05-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_auto_20200430_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='amount',
            field=models.FloatField(default=1),
        ),
    ]
